language: java
sudo: true

script: "mvn cobertura:cobertura"

jdk:
-  openjdk8
services:
-  docker

before_install:
  - chmod +x mvnw
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

after_success:
  - bash <(curl -s https://codecov.io/bash)

addons:
  sonarcloud:
    organization: "coecomber"
    token:
      secure: $SONAR_TOKEN # encrypted value of my token in TRAVIS CI
